baseURL = 'https://barrcodes.dev/'
languageCode = 'en-us'
title = 'BarrCodes'
disableKinds = ['taxonomy', 'term']
cleanDestinationDir = true
markup.highlight.noClasses = false
[markup.goldmark.extensions.passthrough]
enable = true
[markup.goldmark.extensions.passthrough.delimiters]
block = [['$$', '$$']]
inline = [['$', '$']]
[frontmatter]
publishDate = ['publishDate']
[outputFormats.main-only]
mediaType = "text/html"
baseName = "main-only"
[outputFormats.head-only]
mediaType = "text/html"
baseName = "head-only"
[outputs]
home = ['html', 'rss']
section = ['html', 'rss']
[sitemap]
changefreq = "weekly"
